import { WiCloudDown, WiCloudUp, WiCloudy, WiDayFog, WiDayHaze, WiDayLightning, WiDaySunny, WiDirectionDown, WiDirectionRight, WiDirectionUp, WiDust, WiFog, WiHail, WiRain, WiRaindrops, WiRainMix, WiSandstorm, WiShowers, WiSleet, WiSmoke, WiSnow, WiSprinkle, WiStormWarning, WiStrongWind, WiThunderstorm, WiTime1, WiTornado } from 'react-icons/wi'
import { TbSnowflake } from 'react-icons/tb'
import { BsCloudDrizzle} from 'react-icons/bs'
import { IoWarning } from 'react-icons/io5'

const WeatherIcon = ({ code }) => {

    const icons = {
        0: <WiDaySunny />,
        1: <WiCloudDown />,
        2: <WiCloudy />,
        3: <WiCloudUp />,
        4: <WiSmoke />,
        5: <WiDayHaze />,
        6: <WiDust />,
        7: <WiDust />,
        8: <WiSandstorm />,
        9: <WiSandstorm />,
        10: <WiFog />,
        11: <WiFog />,
        12: <WiFog />,
        13: <WiDayLightning />,
        14: <WiRaindrops />,
        15: <WiSprinkle />,
        16: <WiRain />,
        17: <WiDayLightning />,
        18: <WiStrongWind />,
        19: <WiTornado />,
        20: <><WiTime1 /><BsCloudDrizzle /></>,
        21: <><WiTime1 /><WiRain /></>,
        22: <><WiTime1 /><WiSnow /></>,
        23: <><WiTime1 /><WiSleet /></>,
        24: <><WiTime1 /><WiRain /><TbSnowflake /></>,
        25: <><WiTime1 /><WiShowers /></>,
        26: <><WiTime1 /><WiSnow /></>,
        27: <><WiTime1 /><WiHail /></>,
        28: <><WiTime1 /><WiFog /></>,
        29: <><WiTime1 /><WiThunderstorm /></>,
        30: <><WiSandstorm /><WiDirectionDown /></>,
        31: <><WiSandstorm /><WiDirectionRight /></>,
        32: <><WiSandstorm /><WiDirectionUp /></>,
        33: <><WiSandstorm /><WiDirectionDown /><WiStormWarning /></>,
        34: <><WiSandstorm /><WiDirectionRight /><WiStormWarning /></>,
        35: <><WiSandstorm /><WiDirectionUp /><WiStormWarning /></>,
        36: "Leichtes/mäßiges Schneefegen",
        37: "Starkes Schneefegen",
        38: "Leichtes/mäßiges Schneetreiben",
        39: "Starkes Schneetreiben",
        40: "Nebel in der Ferne",
        41: "Nebelschwaden",
        42: "Nebel, Himmel sichtbar, abnehmend",
        43: "Nebel, Himmel verdeckt, abnehmend",
        44: "Nebel, Himmel sichtbar, gleichbleibend",
        45: "Nebel, Himmel verdeckt, gleichbleibend",
        46: "Nebel, Himmel sichtbar, zunehmend",
        47: "Nebel, Himmel verdeckt, zunehmend",
        48: <><WiDayFog /><TbSnowflake /></>,
        49: <><WiFog /><TbSnowflake /></>,
        50: "Leichter Sprühregen, unterbrochen",
        51: "Leichter Sprühregen, anhaltend", 
        52: "Mäßiger Sprühregen, unterbrochen",
        53: "Mäßiger Sprühregen, anhaltend",
        54: "Starker Sprühregen, unterbrochen",
        55: "Starker Sprühregen, anhaltend",
        56: "Gefrierender Sprühregen, leicht",
        57: "Gefrierender Sprühregen, mäßig/stark",
        58: "Leichter Regen und Sprühregen",
        59: "Mäßiger Regen und Sprühregen",
        60: <WiRainMix />,
        61: <WiRain />,
        62: <WiRainMix />,
        63: <WiRain />,
        64: <WiRainMix />,
        65: <WiRain />,
        66: "Gefrierender leichter Regen",
        67: "Gefrierender mäßiger/starker Regen",
        68: "Leichter Schneeregen",
        69: "Mäßiger/Starker Schneeregen",
        70: "Leichter Schneefall, unterbrochen",
        71: "Leichter Schneefall, anhaltend",
        72: "Mäßiger Schneefall, unterbrochen",
        73: "Mäßiger Schneefall, anhaltend",
        74: "Starker Schneefall, unterbrochen",
        75: "Starker Schneefall, anhaltend",
        76: "Eisnadeln",
        77: "Schneegriesel",
        78: "Schneekristalle",
        79: "Eiskörner",
        80: <WiShowers />,
        81: <WiShowers />,
        82: <><WiShowers /><IoWarning /></>,
        83: <WiSleet />,
        84: <WiSleet />,
        85: <WiSnow />,
        86: <WiSnow />,
        87: <><WiSnow /><WiHail /></>,
        88: <><WiSnow /><WiHail /></>,
        89: <WiHail />,
        90: <><WiHail /><IoWarning /></>,
        91: "Leichter Regen, letzte Stunde Gewitter hörbar",
        92: "Starker Regen, letzte Stunde Gewitter hörbar",
        93: "Leichter Schnee/Regen-Hagel, letzte Stunde Gewitter hörbar",
        94: "Starker Schnee/Regen-Hagel, letzte Stunde Gewitter hörbar",
        95: "Leichtes/Mäßiges Gewitter mit Regen/Schnee",
        96: "Leichtes/Mäßiges Gewitter mit Hagel",
        97: "Schweres Gewitter mit Regen/Schnee",
        98: "Gewitter mit Sandsturm",
        99: "Schweres Gewitter mit Hagel"
    }

    if(icons[code] !== undefined)
        return icons[code]
    else
        return icons[~~(code/10) * 10]
}

export default WeatherIcon