import { WiCloudy, WiDayCloudy, WiDayFog, WiDayHaze, WiDayLightning, WiDaySunny, WiDaySunnyOvercast, WiDirectionDown, WiDirectionRight, WiDirectionUp, WiDust, WiFog, WiHail, WiRain, WiRaindrops, WiRainMix, WiSandstorm, WiShowers, WiSleet, WiSmoke, WiSnow, WiSprinkle, WiStormWarning, WiStrongWind, WiThunderstorm, WiTime1, WiTornado } from 'react-icons/wi'
import { TbSnowflake } from 'react-icons/tb'
import { IoWarning } from 'react-icons/io5'
import { StyledTooltip, StyledWeatherIcon } from './WeatherIcon.styled'
import { useState } from 'react'
import { IconContext } from 'react-icons'

const WeatherIcon = ({ code }) => {

    const icons = {
        0: <WiDaySunny />,
        1: <WiDaySunnyOvercast />,
        2: <WiDayCloudy />,
        3: <WiCloudy />,
        4: <WiSmoke />,
        5: <WiDayHaze />,
        6: <WiDust />,
        7: <WiDust />,
        8: <WiSandstorm />,
        9: <WiSandstorm />,
        10: <WiFog />,
        11: <WiFog />,
        12: <WiFog />,
        13: <WiDayLightning />,
        14: <WiRaindrops />,
        15: <WiSprinkle />,
        16: <WiRain />,
        17: <WiDayLightning />,
        18: <WiStrongWind />,
        19: <WiTornado />,
        20: <><WiTime1 /><WiShowers /></>,
        21: <><WiTime1 /><WiRain /></>,
        22: <><WiTime1 /><WiSnow /></>,
        23: <><WiTime1 /><WiSleet /></>,
        24: <><WiTime1 /><WiRain /><TbSnowflake /></>,
        25: <><WiTime1 /><WiShowers /></>,
        26: <><WiTime1 /><WiSnow /></>,
        27: <><WiTime1 /><WiHail /></>,
        28: <><WiTime1 /><WiFog /></>,
        29: <><WiTime1 /><WiThunderstorm /></>,
        30: <><WiSandstorm /><WiDirectionDown /></>,
        31: <><WiSandstorm /><WiDirectionRight /></>,
        32: <><WiSandstorm /><WiDirectionUp /></>,
        33: <><WiSandstorm /><WiDirectionDown /><WiStormWarning /></>,
        34: <><WiSandstorm /><WiDirectionRight /><WiStormWarning /></>,
        35: <><WiSandstorm /><WiDirectionUp /><WiStormWarning /></>,
        36: "Leichtes/mäßiges Schneefegen",
        37: "Starkes Schneefegen",
        38: "Leichtes/mäßiges Schneetreiben",
        39: "Starkes Schneetreiben",
        40: "Nebel in der Ferne",
        41: "Nebelschwaden",
        42: <WiDayFog />,
        43: <WiFog />,
        44: <WiDayFog />,
        45: <WiFog />,
        46: <WiDayFog />,
        47: <WiFog />,
        48: <><WiDayFog /><TbSnowflake /></>,
        49: <><WiFog /><TbSnowflake /></>,
        50: <WiShowers />,
        51: <WiShowers />, 
        52: <WiShowers />,
        53: <WiShowers />,
        54: <WiShowers />,
        55: <WiShowers />,
        56: <><WiShowers /><TbSnowflake /></>,
        57: <><WiShowers /><TbSnowflake /></>,
        58: <WiRain />,
        59: <WiRain />,
        60: <WiRainMix />,
        61: <WiRain />,
        62: <WiRainMix />,
        63: <WiRain />,
        64: <WiRainMix />,
        65: <WiRain />,
        66: <><WiRain/><TbSnowflake/></>,
        67: <><WiRain/><TbSnowflake/></>,
        68: <WiSleet />,
        69: <WiSleet />,
        70: <WiSnow />,
        71: <WiSnow />,
        72: <WiSnow />,
        73: <WiSnow />,
        74: <WiSnow />,
        75: <WiSnow />,
        76: "Eisnadeln",
        77: <WiSleet />,
        78: <TbSnowflake />,
        79: <TbSnowflake />,
        80: <WiShowers />,
        81: <WiShowers />,
        82: <><WiShowers /><IoWarning /></>,
        83: <WiSleet />,
        84: <WiSleet />,
        85: <WiSnow />,
        86: <WiSnow />,
        87: <><WiSnow /><WiHail /></>,
        88: <><WiSnow /><WiHail /></>,
        89: <WiHail />,
        90: <><WiHail /><IoWarning /></>,
        91: "Leichter Regen, letzte Stunde Gewitter hörbar",
        92: "Starker Regen, letzte Stunde Gewitter hörbar",
        93: "Leichter Schnee/Regen-Hagel, letzte Stunde Gewitter hörbar",
        94: "Starker Schnee/Regen-Hagel, letzte Stunde Gewitter hörbar",
        95: <WiThunderstorm />,
        96: <WiThunderstorm />,
        97: <><WiThunderstorm /><IoWarning /></>,
        98: "Gewitter mit Sandsturm",
        99: <><WiThunderstorm /><IoWarning /></>
    }

    const text = {
        0: "Klar",
        1: "Heiter",
        2: "Bewölkt",
        3: "Bedeckt",
        4: "Sicht durch Rauch reduziert",
        5: "Dunst",
        6: "Schwebender Staub, windstill",
        7: "Staub/Sand, von Wind angehoben",
        8: "Staubteufel",
        9: "Staub-/Sandsturm",
        10: "Feuchter Dunst/schwacher Nebel",
        11: "Nebelschwaden am Boden",
        12: "Durchgehender Bodennebel",
        13: "Wetterleuchten",
        14: "Niederschlag sichtbar, erreicht nicht den Boden",
        15: "Niederschlag in der Ferne, erreicht Boden",
        16: "Niederschlag in der Nähe, erreicht Boden",
        17: "Gewitter hörbar, kein Niederschlag",
        18: "Markante Windböen",
        19: "Tornado, Wasserhose, Windhose",
        20: "Nach Sprühregen",
        21: "Nach Regen",
        22: "Nach Schnee",
        23: "Nach Schneeregen",
        24: "Nach gefrierendem Regen",
        25: "Nach Regenschauern",
        26: "Nach Schneeschauern",
        27: "Nach Hagelschauern",
        28: "Nach Nebel",
        29: "Nach Gewitter",
        30: "Leichter/mäßiger Sandsturm, nachlassend",
        31: "Leichter/mäßiger Sandsturm",
        32: "Leichter/mäßiger Sandsturm, zunehmend",
        33: "Schwerer Sandsturm, nachlassend",
        34: "Schwerer Sandsturm",
        35: "Schwerer Sandsturm, zunehmend",
        36: "Leichtes/mäßiges Schneefegen",
        37: "Starkes Schneefegen",
        38: "Leichtes/mäßiges Schneetreiben",
        39: "Starkes Schneetreiben",
        40: "Nebel in der Ferne",
        41: "Nebelschwaden",
        42: "Nebel, Himmel sichtbar, abnehmend",
        43: "Nebel, Himmel verdeckt, abnehmend",
        44: "Nebel, Himmel sichtbar, gleichbleibend",
        45: "Nebel, Himmel verdeckt, gleichbleibend",
        46: "Nebel, Himmel sichtbar, zunehmend",
        47: "Nebel, Himmel verdeckt, zunehmend",
        48: "Raueis mit Nebel, Himmel sichtbar",
        49: "Raueis mit Nebel, Himmel verdeckt",
        50: "Leichter Sprühregen, unterbrochen",
        51: "Leichter Sprühregen, anhaltend", 
        52: "Mäßiger Sprühregen, unterbrochen",
        53: "Mäßiger Sprühregen, anhaltend",
        54: "Starker Sprühregen, unterbrochen",
        55: "Starker Sprühregen, anhaltend",
        56: "Gefrierender Sprühregen, leicht",
        57: "Gefrierender Sprühregen, mäßig/stark",
        58: "Leichter Regen und Sprühregen",
        59: "Mäßiger Regen und Sprühregen",
        60: "Leichter Regen, unterbrochen",
        61: "Leichter Regen, anhaltend",
        62: "Mäßiger Regen, unterbrochen",
        63: "Mäßiger Regen, anhaltend",
        64: "Starker Regen, unterbrochen",
        65: "Starker Regen, anhaltend",
        66: "Gefrierender leichter Regen",
        67: "Gefrierender mäßiger/starker Regen",
        68: "Leichter Schneeregen",
        69: "Mäßiger/Starker Schneeregen",
        70: "Leichter Schneefall, unterbrochen",
        71: "Leichter Schneefall, anhaltend",
        72: "Mäßiger Schneefall, unterbrochen",
        73: "Mäßiger Schneefall, anhaltend",
        74: "Starker Schneefall, unterbrochen",
        75: "Starker Schneefall, anhaltend",
        76: "Eisnadeln",
        77: "Schneegriesel",
        78: "Schneekristalle",
        79: "Eiskörner",
        80: "Leichte Regenschauer",
        81: "Starke Regenschauer",
        82: "Sintflutartige Regenschauer",
        83: "Leichte Schneeregenschauer",
        84: "Starke Schneeregenschauer",
        85: "Leichte Schneeschauer",
        86: "Starke Schneeschauer",
        87: "Leichte Graupelschauer",
        88: "Starke Graupelschauer",
        89: "Leichte Hagelschauer ohne Gewitter",
        90: "Starke Hagelschauer ohne Gewitter",
        91: "Leichter Regen, letzte Stunde Gewitter hörbar",
        92: "Starker Regen, letzte Stunde Gewitter hörbar",
        93: "Leichter Schnee/Regen-Hagel, letzte Stunde Gewitter hörbar",
        94: "Starker Schnee/Regen-Hagel, letzte Stunde Gewitter hörbar",
        95: "Leichtes/Mäßiges Gewitter mit Regen/Schnee",
        96: "Leichtes/Mäßiges Gewitter mit Hagel",
        97: "Schweres Gewitter mit Regen/Schnee",
        98: "Gewitter mit Sandsturm",
        99: "Schweres Gewitter mit Hagel"
    }

    const [showtooltip, setShowtooltip] = useState(false)

    const toggleTooltip = () => {
        setShowtooltip(!showtooltip)
    }

    if(icons[code] !== undefined)
        return(
            <IconContext.Provider value={{ size: "64px" }}>
            <StyledWeatherIcon onClick={toggleTooltip} title={text[code]}>
                {showtooltip ? <Tooltip text={text[code]} onClick={toggleTooltip}/> : <></>}
                {icons[code]}
            </StyledWeatherIcon>
            </IconContext.Provider>
        )
    else
        return(<></>)
}

const Tooltip = ({ text }) => {

    return(<StyledTooltip>
        {text !== undefined ? text : <></>}
    </StyledTooltip>)
}

export default WeatherIcon