name: Dev Upload

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'master'
        type: string
    secrets:
      FPT_PASSWORD:
        required: true
      SCP_HOST:
        required: true
      SCP_USER:
        required: true
      SCP_PASSWORD:
        required: true
      SCP_PORT:
        required: true
      MAPTILER_API_KEY:
        required: true
  schedule:
    - cron: '30 */12 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
      options: --dns 8.8.8.8
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - run: echo "Deploying ${{ inputs.branch }} to RPI"
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Alter package.json
        uses: jossef/action-set-json-field@v2.2
        with:
          file: package.json
          field: homepage
          value: /alpha/
      - name: Alter manifest.json
        uses: jossef/action-set-json-field@v2.2
        with:
          file: public/manifest.json
          field: start_url
          value: /alpha/
      - name: Alter manifest.json
        uses: jossef/action-set-json-field@v2.2
        with:
          file: public/manifest.json
          field: scope
          value: /alpha/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
        env:
          REACT_APP_MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
          REACT_APP_SERVICE_CELL: ${{ secrets.SERVICE_CELL }}
      - name: Deploy to RPI
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USER }}
          password: ${{ secrets.SCP_PASSWORD }}
          port: ${{ secrets.SCP_PORT }}
          source: "./build/"
          target: "/home/pog/deploy/"
          rm: true
  deploy:
    runs-on: [self-hosted, Linux, ARM64]
    needs: build
    steps:
      - name: Upload Website files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: spzroenkhausen.bplaced.net
          username: spzroenkhausen_admin
          password: ${{ secrets.FPT_PASSWORD }}
          local-dir: /home/pog/deploy/build/
          server-dir: ./www/alpha/
