name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 15.x]
      
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
        
      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: spzroenkhausen.bplaced.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FPT_PASSWORD }}
          local-dir: ./build/
          server-dir: ./www/
