name: Publish

on:
  create:
    tags:
      -'v[0-9].*.*'
    
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    if: github.event.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
        env:
          VITE_MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}
          VITE_SERVICE_CELL: ${{ secrets.SERVICE_CELL }}
        
      - name: Upload Website files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: spzroenkhausen.bplaced.net
          username: spzroenkhausen_admin
          password: ${{ secrets.FPT_PASSWORD }}
          local-dir: ./build/
          server-dir: ./www/