name: Test PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build-deploy:
    uses: tritolium/spz_planner/.github/workflows/dev_upload.yml@master
    secrets: inherit

  test:
    needs: build-deploy
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Delete log
      run: wget https://spzroenkhausen.bplaced.net/api/playwright.php --method DELETE