name: Test PR

concurrency: alpha

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  build-deploy:
    uses: tritolium/spz_planner/.github/workflows/dev_upload.yml@master
    secrets: 
      FPT_PASSWORD: ${{ secrets.FPT_PASSWORD }}
      SCP_HOST: ${{ secrets.SCP_HOST }}
      SCP_PASSWORD: ${{ secrets.SCP_PASSWORD }}
      SCP_USER: ${{ secrets.SCP_USER }}
      MAPTILER_API_KEY: ${{ secrets.MAPTILER_API_KEY }}

  test:
    needs: build-deploy
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Delete log
      run: wget https://spzroenkhausen.bplaced.net/api/playwright.php --method DELETE
  
  dependabot:
    name: 'Dependabot automerger'
    runs-on: ubuntu-latest
    needs: [build-deploy, test]
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}